// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxoWmjTZOaxHu5Ugjg5ocbzKRuO9LKRCg',
    appId: '1:925445635042:web:cf2eee53f47c05ec1897bb',
    messagingSenderId: '925445635042',
    projectId: 'comp-sci-nea-60eb8',
    authDomain: 'comp-sci-nea-60eb8.firebaseapp.com',
    storageBucket: 'comp-sci-nea-60eb8.firebasestorage.app',
    measurementId: 'G-WSSXSCV0FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYuMIQM_wEs0FZmuvDqUKdPuft_cl6RLc',
    appId: '1:925445635042:android:e7b3d2db236caa5e1897bb',
    messagingSenderId: '925445635042',
    projectId: 'comp-sci-nea-60eb8',
    storageBucket: 'comp-sci-nea-60eb8.firebasestorage.app',
  );
}
